# Generated by Django 3.2.4 on 2021-06-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('worker_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerStats',
            fields=[
                ('stats_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('worker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='BeautySaloonApplication.worker')),
            ],
        ),
    ]
