# Generated by Django 3.2.4 on 2021-06-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BeautySaloonApplication', '0003_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
