# Generated by Django 3.2.4 on 2021-06-18 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BeautySaloonApplication', '0004_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='BeautySaloonApplication.service'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
