# Generated by Django 3.2.4 on 2021-06-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeautySaloonApplication', '0005_auto_20210618_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='surname',
        ),
    ]
