# Generated by Django 3.2.4 on 2021-06-19 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BeautySaloonApplication', '0006_remove_client_surname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='workerstats',
            name='worker',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.DeleteModel(
            name='WorkerStats',
        ),
    ]
